# @package _group_
# Contains all the demo components with default version
manifest:
  # HELLO WORLD COMPONENT
  - key: "HelloWorldComponent"
    name: "helloworldcomponent"
    version: null
    yaml: "hello_world/component_spec.yaml"
  # COMPONENT THAT OPERATES ON A PARAMETER VALUE
  # - key: # To-Do
  #   name: # To-Do
  #   version: null
  #   yaml: # To-Do
  # COMPONENT THAT COUNTS ROWS IN THE INPUT DATASET
  - key: "CountRows"
    name: "countrows"
    version: null
    yaml: "count_rows/component_spec.yaml"
  # COMPONENT THAT COUNTS ROWS IN THE INPUT DATASET WITH COMPLIANT LOGGING
  - key: "CountRowsAndLog"
    name: "countrowsandlog"
    version: null
    yaml: "count_rows_and_log/component_spec.yaml"
  # COMPONENT THAT EXPERIMENTS WITH DATA CATEGORY
  - key: "LogDataCategory"
    name: "logdatacategorycomponent"
    version: null
    yaml: "log_data_category/component_spec.yaml"
  # COMPONENT THAT USES STACK TRACE PREFIXING
  - key: "LogStackTracePrefixing"
    name: "logstacktraceprefixingcomponent"
    version: null
    yaml: "log_stack_trace_prefixing/component_spec.yaml"
  # PROBE COMPONENT  
  - key: "probe"
    name: "probe"
    version: null
    yaml: "probe/component_spec.yaml"