name: scriptrun-1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.8"
    - name: requirements
      run: pip install azureml-sdk>=1.20.0
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: submit to azure
      run: |
        cd problem-sets/scriptrun/1-data
        python azureml_upload.py
        python azureml_submit.py